### ISSUE TITLE
[CKEditor 5] CKEditor error: view-writer-invalid-range-container. Error when adding a formula on a TodoList

### ISSUE THREAD

**Issue by FilipTokarski** [wiris/html-integrations#11]
Tested on new version, branch `ckeditor5-demo`

#### Steps to reproduce:
   - add MathType formula as an item on TodoList
   - Chrome/Safari version: press `left arrow` or select formula and press space
   
     Firefox version: just press `space` after adding formula
     
   There is also a different way to reproduce this error:
   - add MathType formula as an item on TodoList
   - place the caret just before the formula and try to type
     

Result:
   ```js
    Uncaught CKEditorError: view-writer-invalid-range-container
    at validateRangeContainer (http://localhost:5500/dist/bundle.js:39157:9)
    at DowncastWriter.remove (http://localhost:5500/dist/bundle.js:37946:3)
    at DowncastDispatcher.<anonymous> (http://localhost:5500/dist/bundle.js:9286:40)
    at DowncastDispatcher.fire (http://localhost:5500/dist/bundle.js:77176:30)
    at DowncastDispatcher.convertRemove (http://localhost:5500/dist/bundle.js:8399:8)
    at DowncastDispatcher.convertChanges (http://localhost:5500/dist/bundle.js:8325:10)
    at http://localhost:5500/dist/bundle.js:7394:29
    at View.change (http://localhost:5500/dist/bundle.js:47808:27)
    at Document.EditingController.listenTo.priority (http://localhost:5500/dist/bundle.js:7393:14)
    at Document.fire (http://localhost:5500/dist/bundle.js:77176:30)
   ```

**Comment by FilipTokarski** [comment]
Hi, I just checked this issue once again with the new MathType version 7.24.1 and it's mostly fixed. Chrome and Safari work fine now, the only thing that crashes is Firefox.
  
### Steps:
In Firefox:
1. Add a todo list item
2. Insert formula
3. Press `space`
  
![0_mathtype1](https://user-images.githubusercontent.com/34380544/95453301-de8e8e80-096a-11eb-8bf3-6c26b89a7174.gif)
  
```js
Uncaught CKEditorError: modelWriter.createElement is not a function Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-modelWriter.createElement is not a function
    model plugin.js:219
    getModelElement upcasthelpers.js:794
    prepareToElementConverter upcasthelpers.js:770
    fire emittermixin.js:209
    _convertItem upcastdispatcher.js:249
    _convertChildren upcastdispatcher.js:282
    convertToModelFragment upcasthelpers.js:448
    fire emittermixin.js:209
    _convertItem upcastdispatcher.js:249
    convert upcastdispatcher.js:207
    toModel datacontroller.js:414
    _runPendingChanges model.js:830
    change model.js:175
    toModel datacontroller.js:413
    _handleContainerChildrenMutations injecttypingmutationshandling.js:109
    handle injecttypingmutationshandling.js:64
    injectTypingMutationsHandling injecttypingmutationshandling.js:22
    fire emittermixin.js:209
    _onMutations mutationobserver.js:249
    MutationObserver mutationobserver.js:78
    addObserver view.js:343
    View view.js:181
    EditingController editingcontroller.js:51
    Editor editor.js:185
    ClassicEditor classiceditor.js:63
    create classiceditor.js:195
    create classiceditor.js:194
    js app.js:26
```
### Notes:  
- typing around formula works fine in all browsers

**Comment by xaviripo** [comment]
The bug is on CKEditor's or Firefox's side, it will eventually be solved once Firefox supports the `beforeInput` event properly. I will close this issue but will also mark it so we don't forget about this.
